### ISSUE TITLE
Question regarding walls

### ISSUE THREAD

**Issue by ogencoglu** [dragonHyeon/HomeGAN#1]
Does your work generate only images or does it also output details of wall instances (start & end points of each wall segment)?

**Comment by dragonHyeon** [comment]
Hi Gencoglu!

This only generates images since it only uses image data to train the model.

If you need start & end points, you should extract them from the ouput image data by yourself.
(I guess using _morphological transformations_, _binarization_, _thinning_, and _chain code_ might help to extract those instances.)

Hope you got some intuition!

**Comment by dragonHyeon** [comment]
Hi Gencoglu!

**This only generates images** since it only uses image data to train the model.

If you need start & end points, you should extract them from the ouput image data by yourself.
(I guess using _morphological transformations_, _binarization_, _thinning_, and _chain code_ might help to extract those instances.)

Hope you got some intuition!

**Comment by ogencoglu** [comment]
Thanks for the swift reply!
